### ISSUE TITLE
Incompatible with GNU bash version 4.1.2

### ISSUE THREAD

**Issue by lamskoy** [Dieterbe/libui-sh#1]
I was building custom archiso and aif was not working correctly.

Welcome to Arch Linux Installation Framework
dirname: extra operand 'PROCEDURE'
Try 'dirname --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
ERROR: Cannot create log directory 

After debugging I found problem in libui.sh:
functions log() debug() and check_is_in()

Will priovide a patch for you

**Comment by lamskoy** [comment]
I've placed it at: http://pastebin.com/AqjrEES4

**Comment by Dieterbe** [comment]
can you break down what exactly the problems are, and why the changes are needed? were you using bash? which version?
It's suprising that it wouldn't work as it does work on regular archiso images

**Comment by lamskoy** [comment]
That's no more actual. You can close it.
