### ISSUE TITLE
What's the meaning of '< <(_dia_dialog ...)' at line 428 and line 558

### ISSUE THREAD

**Issue by zhaoyuankui** [Dieterbe/libui-sh#5]
Hello! I met a problem when sourcing the libui.sh. Here is the error:

> ../libui.sh: line 428: syntax error near unexpected token `<'
../libui.sh: line 428: `        done < <(_dia_dialog --separate-output $elab --checklist "$str" 0 0 0 "${list[@]}")'

I found two locations with the code like '< <(_dia_dialog ...)', but don't known what's the meaning. In my opionion, it should be '< $(_dia_dialog ...)'. The following are the source code from libui.sh:
` done < <(_dia_dialog --separate-output $elab --checklist "$str" 0 0 0 "${list[@]}")`
` done < <(_dia_dialog --form "$formtitle" 15 50 0 "${items[@]}")`

Can anyone help me? Thanks!

**Comment by Dieterbe** [comment]
are you using bash or a different shell?
afaik this is standard bash syntax.

**Comment by zhaoyuankui** [comment]
I'm sure using the GNU bash. Below is my test code:
`#!/bin/bash

source ../libui.sh;

die_error 'Ooh! Died!';`

The bash version info is:

> /bin/bash --version
GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

I want to know what's the semantics of '< <(...)'. Does it an input redirection, or a heredoc, or anything else?

**Comment by Dieterbe** [comment]
Afaik it executes the command and feeds the stdout of it into stdin of the loop. I'm afk

**Comment by zhaoyuankui** [comment]
I got it. Many thanks！

**Comment by zhaoyuankui** [comment]
I tried to find any documents of this usage, but it's in vain. However, I found a solution, within my knowledge domain, to solve this problem. The answer is using heredoc like this:
done << DELIMITER
$(_dia_dialog --separate-output $elab --checklist "$str" 0 0 0 "${list[@]}")
DELIMITER

Thank you again!

**Comment by Dieterbe** [comment]
https://stackoverflow.com/questions/2443085/what-does-cmd-args-mean-in-the-shell
